// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEpoSfhdDODKD6R-Av4Chd7Ih_kt6Oe74',
    appId: '1:176971316006:web:c6ebe0e6b27c68ed909fe7',
    messagingSenderId: '176971316006',
    projectId: 'warehouse-management-too-c92ba',
    authDomain: 'warehouse-management-too-c92ba.firebaseapp.com',
    storageBucket: 'warehouse-management-too-c92ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYM9Qf_Ab7TIaW1qglX6wWYtXvDihYx4',
    appId: '1:176971316006:android:09b3ac1da095a6de909fe7',
    messagingSenderId: '176971316006',
    projectId: 'warehouse-management-too-c92ba',
    storageBucket: 'warehouse-management-too-c92ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtyCqHpXTP6AY6qWqVf07OzZq4ocm0lzw',
    appId: '1:176971316006:ios:59e93f5230ebaf8d909fe7',
    messagingSenderId: '176971316006',
    projectId: 'warehouse-management-too-c92ba',
    storageBucket: 'warehouse-management-too-c92ba.appspot.com',
    iosBundleId: 'com.example.wmtTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtyCqHpXTP6AY6qWqVf07OzZq4ocm0lzw',
    appId: '1:176971316006:ios:4c16aa03c6158c0b909fe7',
    messagingSenderId: '176971316006',
    projectId: 'warehouse-management-too-c92ba',
    storageBucket: 'warehouse-management-too-c92ba.appspot.com',
    iosBundleId: 'com.example.wmtTest.RunnerTests',
  );
}
